In [1]:
from tkinter import Tk, filedialog
import pandas as pd

# Masquer la fenêtre principale Tkinter
root = Tk()
root.withdraw()

# Forcer la fenêtre à être au premier plan
root.attributes('-topmost', True)
root.update()

# Ouvrir la fenêtre de sélection
fichier = filedialog.askopenfilename(
    title="Choisissez le fichier à analyser",
    filetypes=[("Fichiers CSV", "*.csv"), ("Fichiers Excel", "*.xlsx *.xls"), ("Tous les fichiers", "*.*")]
)

# Lecture du fichier sélectionné avec pandas
df = pd.read_csv(fichier)

In [2]:
df.columns

Index(['Severity', 'Start_Time', 'End_Time', 'Start_Lat', 'Start_Lng',
       'Distance(mi)', 'Street', 'City', 'County', 'State', 'Zipcode',
       'Timezone', 'Airport_Code', 'Humidity(%)', 'Visibility(mi)',
       'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Condition', 'Amenity',
       'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway',
       'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal',
       'Turning_Loop', 'Sunrise_Sunset', 'year', 'month', 'time',
       'day_of_week', 'is_weekend', 'season', 'day_period', 'Duration_Minutes',
       'Impact_Social', 'Weather_Category', 'Temperature_C', 'hour',
       'Temperature_Category', 'hour_bucket', 'Precipitation_Category',
       'Visibility_Category', 'Humidity_Category', 'Wind_Category',
       'Infrastructure_Count', 'Infrastructure_Density', 'Has_Infrastructure',
       'Safety_Device_Count', 'Has_Safety_Device', 'Conflict_Point_Count',
       'Has_Conflict_Point', 'Activity_Zone_Count', 'Is_Activity_Zone',
       'Is_Isolated', 'Safety_Conflict_Ratio', 'Safety_Level',
       'High_Risk_Junction', 'Junction_With_Signal', 'Junction_With_Stop',
       'Junction_With_Roundabout', 'Junction_With_GiveWay_Only',
       'Crossing_Without_Signal', 'Is_Railway_Area', 'High_Activity_Zone',
       'Junction_Type', 'Calming_Type', 'Risk_Points',
       'Infrastructure_Risk_Score', 'Infrastructure_Risk_Category',
       'Protection_Index', 'Protection_Level', 'Region', 'Zone_Type',
       'Accident_Count_By_State', 'Accident_Density_Level', 'State_Risk_Level',
       'Is_High_Accident_State'],
      dtype='object')

## Echantillonnage

### Vérification de la couverture

In [3]:
pd.crosstab(df['State'], df['month'])

month,1,2,3,4,5,6,7,8,9,10,11,12
State,,,,,,,,,,,,
AL,9065,7679,8148,8415,8105,8160,7309,8094,7996,8726,9462,9726
AR,2665,2130,1456,1535,1416,1647,1259,1496,1937,1815,2618,2756
AZ,15964,13403,12765,15001,13782,12047,10449,13877,13951,13535,16268,16821
CA,168139,156995,139146,139066,125658,131025,108187,124308,147611,147131,164672,187538
CO,8898,8155,7534,6979,6657,6948,5962,7326,6986,7786,8017,9448
CT,6066,5631,4517,5122,4796,5938,5505,5462,6531,6828,7537,7020
DC,1733,1275,1167,1673,1474,1459,1236,1219,1809,1613,1857,2053
DE,982,998,980,1146,1183,1307,1223,1145,1144,1207,1283,1180
FL,89319,72020,63022,71695,65019,57907,52885,62078,71903,77407,92117,101398
GA,16040,14104,12893,11705,11160,11617,11528,14258,14177,15203,16743,19564
IA,3374,3209,1442,1620,1539,1721,1629,1699,1771,2000,2433,3697
ID,1074,1227,705,911,710,846,515,625,727,952,1159,1752
IL,15330,15045,11610,11684,12794,15199,13506,14436,13939,15475,15162,14651
IN,6529,6410,4355,4434,4751,5229,5334,6139,6620,6117,4817,6389
KS,2002,2582,1660,1211,1394,1434,1314,1600,1604,1632,2199,2064
KY,2524,2600,2442,2355,2433,2799,2569,3048,2969,3177,2736,2557
LA,12886,10434,9756,11167,10818,9480,8813,13006,13663,12560,13564,14218
MA,5347,5407,4511,4536,4775,5273,4511,5426,5252,5561,5997,5386
MD,13391,10926,9710,11525,9953,10939,9721,10102,11570,12260,14256,15981
ME,207,233,169,155,178,224,288,309,230,212,210,262
MI,16736,15478,11269,10845,11318,12074,11943,13319,13998,13990,14816,16302
MN,28133,21995,10762,11022,10216,11400,8848,10853,11789,16117,17543,33153
MO,7309,8320,5855,5663,5666,5866,5282,5850,6144,6553,7177,7519
MS,1558,1421,1131,1150,982,877,1080,1309,1342,1237,1412,1641
MT,3518,2733,1334,2155,345,538,783,1349,1532,1783,4006,6523
NC,31297,26911,25851,28377,26501,23978,21483,27715,27657,29472,33961,34612
ND,684,200,200,69,158,165,225,212,190,205,528,647
NE,2409,2385,2007,2348,2398,2499,2114,2486,2364,2698,2326,2464
NH,1072,1101,754,639,630,835,670,852,720,844,978,1085
NJ,11428,13364,10125,10013,11833,12163,11035,11320,12337,12599,11957,12255
NM,861,905,763,690,715,908,690,885,859,1019,954,1048
NV,2082,1955,1409,1329,1471,1657,1692,2004,1811,1669,1939,2438
NY,28591,27899,21735,24702,29001,31419,27157,29863,32645,31965,30982,31390
OH,12785,7627,7521,8853,8358,8950,7004,7978,8053,10485,14463,15937
OK,6373,5663,6202,7068,7406,6238,5730,7890,6655,6515,7053,6882
OR,19222,19777,11327,10211,9084,11351,9619,12816,14190,14364,18724,25087
PA,30852,25949,20071,21068,19926,21829,19638,21783,24283,24762,31542,34418
RI,1248,1360,1114,1337,1311,1480,1315,1558,1652,1503,1658,1433
SC,37022,28628,26011,29389,28259,27496,26121,31970,32780,35775,38003,40553
SD,11,10,8,4,6,3,3,26,97,70,9,27
TN,14249,12888,11681,13617,13073,12031,11606,15518,15085,14692,15892,16969
TX,54406,45701,40574,41722,39481,41649,42902,50529,52975,52925,59944,59638
UT,9753,8852,6826,6506,7248,8047,6253,7559,7081,7604,8528,12538
VA,30375,20810,19051,23493,20694,21704,20697,23354,26182,28010,32874,35872
VT,81,105,88,39,30,71,66,72,81,81,92,119
WA,8686,8361,7472,7175,7665,9094,9069,8971,9226,9862,10498,11646
WI,3512,3187,1951,2416,2598,2859,2494,3018,2906,2813,3450,3454
WV,1440,1364,1042,886,763,933,1075,818,1010,1135,1490,1639
WY,730,304,294,196,78,76,81,100,82,239,373,832

### échantillonnage stratifié State × Month

#### prendre 10% de chaque (State, month)

In [4]:
sample_frac = 0.10  # 10%

df_sample = (
    df
    .groupby(['State', 'month'], group_keys=False)
    .apply(lambda x: x.sample(
        frac=sample_frac,
        random_state=42
    ) if len(x) > 1 else x)
)

C:\Users\pc\AppData\Local\Temp\ipykernel_11592\3265811181.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(

#### Tous les États ≈ même proportion relative que le dataset initial

In [8]:
df['State'].value_counts(normalize=True)

State
CA    0.226099
FL    0.113964
TX    0.075707
SC    0.049654
NY    0.045149
NC    0.043910
VA    0.039399
PA    0.038490
MN    0.024934
OR    0.022847
GA    0.021966
IL    0.021945
AZ    0.021819
TN    0.021746
MI    0.021068
NJ    0.018253
LA    0.018245
MD    0.018241
OH    0.015340
WA    0.014002
AL    0.013113
UT    0.012582
CO    0.011789
OK    0.010356
MO    0.010035
CT    0.009223
IN    0.008725
MA    0.008057
WI    0.004505
KY    0.004187
NE    0.003704
MT    0.003457
IA    0.003397
AR    0.002954
NV    0.002789
KS    0.002690
DC    0.002413
RI    0.002206
MS    0.001968
DE    0.001791
WV    0.001767
ID    0.001456
NM    0.001338
NH    0.001323
ND    0.000453
WY    0.000440
ME    0.000348
VT    0.000120
SD    0.000036
Name: proportion, dtype: float64

In [5]:
df_sample['State'].value_counts(normalize=True)

State
CA    0.226100
FL    0.113965
TX    0.075706
SC    0.049654
NY    0.045148
NC    0.043910
VA    0.039397
PA    0.038490
MN    0.024934
OR    0.022847
GA    0.021964
IL    0.021945
AZ    0.021819
TN    0.021746
MI    0.021069
NJ    0.018253
LA    0.018245
MD    0.018240
OH    0.015338
WA    0.014003
AL    0.013114
UT    0.012582
CO    0.011792
OK    0.010357
MO    0.010036
CT    0.009223
IN    0.008726
MA    0.008059
WI    0.004505
KY    0.004188
NE    0.003704
MT    0.003456
IA    0.003396
AR    0.002958
NV    0.002789
KS    0.002687
DC    0.002414
RI    0.002206
MS    0.001968
DE    0.001790
WV    0.001768
ID    0.001456
NM    0.001338
NH    0.001322
ND    0.000451
WY    0.000439
ME    0.000348
VT    0.000120
SD    0.000036
Name: proportion, dtype: float64

#### Vérifier que les 12 mois apparaissent

In [6]:
df_sample['month'].value_counts().sort_index()

month
1     74794
2     65571
3     55240
4     58495
5     55581
6     56941
7     51041
8     59765
9     64811
10    67218
11    75628
12    84259
Name: count, dtype: int64

#### Vérifier que aucune cellule vide (ou très peu)

In [7]:
pd.crosstab(df_sample['State'], df_sample['month'])

month,1,2,3,4,5,6,7,8,9,10,11,12
State,,,,,,,,,,,,
AL,906,768,815,842,810,816,731,809,800,873,946,973
AR,266,213,146,154,142,165,126,150,194,182,262,276
AZ,1596,1340,1276,1500,1378,1205,1045,1388,1395,1354,1627,1682
CA,16814,15700,13915,13907,12566,13102,10819,12431,14761,14713,16467,18754
CO,890,816,753,698,666,695,596,733,699,779,802,945
CT,607,563,452,512,480,594,550,546,653,683,754,702
DC,173,128,117,167,147,146,124,122,181,161,186,205
DE,98,100,98,115,118,131,122,114,114,121,128,118
FL,8932,7202,6302,7170,6502,5791,5288,6208,7190,7741,9212,10140
GA,1604,1410,1289,1170,1116,1162,1153,1426,1418,1520,1674,1956
IA,337,321,144,162,154,172,163,170,177,200,243,370
ID,107,123,70,91,71,85,52,62,73,95,116,175
IL,1533,1504,1161,1168,1279,1520,1351,1444,1394,1548,1516,1465
IN,653,641,436,443,475,523,533,614,662,612,482,639
KS,200,258,166,121,139,143,131,160,160,163,220,206
KY,252,260,244,236,243,280,257,305,297,318,274,256
LA,1289,1043,976,1117,1082,948,881,1301,1366,1256,1356,1422
MA,535,541,451,454,478,527,451,543,525,556,600,539
MD,1339,1093,971,1152,995,1094,972,1010,1157,1226,1426,1598
ME,21,23,17,16,18,22,29,31,23,21,21,26
MI,1674,1548,1127,1084,1132,1207,1194,1332,1400,1399,1482,1630
MN,2813,2200,1076,1102,1022,1140,885,1085,1179,1612,1754,3315
MO,731,832,586,566,567,587,528,585,614,655,718,752
MS,156,142,113,115,98,88,108,131,134,124,141,164
MT,352,273,133,216,34,54,78,135,153,178,401,652
NC,3130,2691,2585,2838,2650,2398,2148,2772,2766,2947,3396,3461
ND,68,20,20,7,16,16,22,21,19,20,53,65
NE,241,238,201,235,240,250,211,249,236,270,233,246
NH,107,110,75,64,63,84,67,85,72,84,98,108
NJ,1143,1336,1012,1001,1183,1216,1104,1132,1234,1260,1196,1226
NM,86,90,76,69,72,91,69,88,86,102,95,105
NV,208,196,141,133,147,166,169,200,181,167,194,244
NY,2859,2790,2174,2470,2900,3142,2716,2986,3264,3196,3098,3139
OH,1278,763,752,885,836,895,700,798,805,1048,1446,1594
OK,637,566,620,707,741,624,573,789,666,652,705,688
OR,1922,1978,1133,1021,908,1135,962,1282,1419,1436,1872,2509
PA,3085,2595,2007,2107,1993,2183,1964,2178,2428,2476,3154,3442
RI,125,136,111,134,131,148,132,156,165,150,166,143
SC,3702,2863,2601,2939,2826,2750,2612,3197,3278,3578,3800,4055
SD,1,1,1,0,1,0,0,3,10,7,1,3
TN,1425,1289,1168,1362,1307,1203,1161,1552,1508,1469,1589,1697
TX,5441,4570,4057,4172,3948,4165,4290,5053,5298,5292,5994,5964
UT,975,885,683,651,725,805,625,756,708,760,853,1254
VA,3038,2081,1905,2349,2069,2170,2070,2335,2618,2801,3287,3587
VT,8,10,9,4,3,7,7,7,8,8,9,12
WA,869,836,747,718,766,909,907,897,923,986,1050,1165
WI,351,319,195,242,260,286,249,302,291,281,345,345
WV,144,136,104,89,76,93,108,82,101,114,149,164
WY,73,30,29,20,8,8,8,10,8,24,37,83

Un échantillonnage stratifié par État et par mois a été appliqué afin d’assurer une représentation équitable des régions et des variations saisonnières dans l’analyse statistique.

In [9]:
df_sample.shape

(769344, 83)

## Statistique Inférentielle

### Comparer Severity entre 2 groupes : pluie vs sec (Test t ou Mann-Whitney)

Variable continue : Severity

Deux groupes : Rain vs Dry (Clear, Cloudy, Fog)

On teste :

- H0: la moyenne de Severity est la meme dans les 2 groupes
- H1​:les moyennes sont différentes

Interprétation:

- t_stat → mesure la différence entre les moyennes en termes d’écart-type.
- p_val → probabilité d’obtenir cette différence si H0 est vraie.

p < 0.05 → la météo influence significativement la gravité.

In [12]:
from scipy.stats import ttest_ind, mannwhitneyu

# Séparer les groupes
rain_severity = df_sample[df_sample['Weather_Category']=='Rain']['Severity']
dry_severity = df_sample[df_sample['Weather_Category'].isin(['Clear','Cloudy','Fog'])]['Severity']

# Test t 2 échantillons
t_stat, p_val = ttest_ind(rain_severity, dry_severity, equal_var=False)
print(f"T-test (Rain vs Dry): t={t_stat:.3f}, p={p_val:.5f}")

# Test non-paramétrique (si la distribution n'est pas normale)
u_stat, p_val_u = mannwhitneyu(rain_severity, dry_severity)
print(f"Mann-Whitney (Rain vs Dry): U={u_stat}, p={p_val_u:.5f}")

T-test (Rain vs Dry): t=19.488, p=0.00000
Mann-Whitney (Rain vs Dry): U=18539246198.5, p=0.00000

### ANOVA pour comparer Severity entre plusieurs catégories (Weather_Category)

ANOVA = Analysis Of Variance répond à la question :

Les différences observées entre groupes sont-elles réelles ou dues au hasard ?

sum_sq (Somme des carrés):

- Mesure la variabilité
- Plus elle est grande → plus la variable explique la variation de Severity

df (degrés de liberté):

- Liés au nombre de catégories météo

F (statistique F):
- F élevé → groupes très différents
- F proche de 1 → groupes similaires

PR(>F) (p-value):
- < 0.05 → Différence significative
- < 0.01 → Très significative
- ≥ 0.05 → Pas de preuve de différence

In [14]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

model = ols('Severity ~ C(Weather_Category)', data=df_sample).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
print(anova_table)

                            sum_sq        df           F  PR(>F)
C(Weather_Category)     594.843584       8.0  314.207422     0.0
Residual             182058.871414  769335.0         NaN     NaN

### Corrélation entre variables continues

#### Pearson mesure la relation linéaire entre deux variables continues.

Quand la vitesse du vent augmente, est-ce que la distance de l’accident augmente ou diminue de façon linéaire ?

Résultats retournés:
- r → coefficient de corrélation (entre -1 et +1)
- p → p-value (significativité statistique)

r ≈ 0 → Pas de relation linéaire

p = 0.0000 → le lien n’est pas dû au hasard

#### Spearman mesure une relation monotone (pas forcément linéaire), basée sur le classement des valeurs.
Quand la visibilité diminue, est-ce que la sévérité tend à augmenter globalement, même si la relation n’est pas linéaire ?

Résultats retournés:
- rho → coefficient de corrélation monotone
- p_s → significativité

rho = -0.09 → négatif dnc quand visibilité ↓ → sévérité ↑

In [18]:
from scipy.stats import spearmanr, pearsonr

subset_s = df_sample[['Severity', 'Visibility(mi)']].dropna()
subset_p = df_sample[['Wind_Speed(mph)', 'Distance(mi)']].dropna()


# Pearson pour linéaire
r, p = pearsonr(
    subset_p['Wind_Speed(mph)'],
    subset_p['Distance(mi)']
)
print(f"Pearson Wind vs Distance: r={r:.3f}, p={p:.5f}")


# Spearman pour rangs
rho, p_s = spearmanr(
    subset_s['Severity'],
    subset_s['Visibility(mi)']
)
print(f"Spearman Severity vs Visibility: rho={rho:.3f}, p={p_s:.5f}")

Pearson Wind vs Distance: r=0.011, p=0.00000
Spearman Severity vs Visibility: rho=-0.009, p=0.00000

### Régression linéaire simple et multiple

Comment lire lm2.summary() :

| Élément            | Signification           |
| ------------------ | ----------------------- |
| R-squared          | % de variance expliquée |
| Adj. R-squared     | R² pénalisé             |
| F-statistic        | Significativité globale |
| Prob (F-statistic) | p-value globale         |

In [20]:
import statsmodels.formula.api as smf

# Multiple : Severity ~ Weather + Visibility + Wind
lm2 = smf.ols(
    'Severity ~ C(Weather_Category) + Q("Visibility(mi)") + Q("Wind_Speed(mph)")',
    data=df_sample
).fit()

print(lm2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               Severity   R-squared:                       0.004
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     277.2
Date:                Thu, 15 Jan 2026   Prob (F-statistic):               0.00
Time:                        15:47:13   Log-Likelihood:            -5.3180e+05
No. Observations:              763337   AIC:                         1.064e+06
Df Residuals:                  763326   BIC:                         1.064e+06
Df Model:                          10
Covariance Type:            nonrobust
===============================================================================================================
                                                  coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------------
Intercept                                       2.1547      0.003    752.154      0.000       2.149       2.160
C(Weather_Category)[T.Cloudy]                   0.0492      0.001     40.847      0.000       0.047       0.052
C(Weather_Category)[T.Extreme]                 -0.0880      0.051     -1.727      0.084      -0.188       0.012
C(Weather_Category)[T.Fog]                      0.0099      0.004      2.469      0.014       0.002       0.018
C(Weather_Category)[T.Rain]                     0.0717      0.003     28.261      0.000       0.067       0.077
C(Weather_Category)[T.Snow]                     0.0566      0.004     12.873      0.000       0.048       0.065
C(Weather_Category)[T.Thunderstorm]             0.0371      0.005      6.990      0.000       0.027       0.048
C(Weather_Category)[T.Unknown]                 -0.0433      0.027     -1.620      0.105      -0.096       0.009
C(Weather_Category)[T.Wintry precipitation]     0.0093      0.014      0.681      0.496      -0.018       0.036
Q("Visibility(mi)")                             0.0018      0.000      6.548      0.000       0.001       0.002
Q("Wind_Speed(mph)")                            0.0018      0.000     17.570      0.000       0.002       0.002
==============================================================================
Omnibus:                   258804.696   Durbin-Watson:                   1.917
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           764194.886
Skew:                           1.807   Prob(JB):                         0.00
Kurtosis:                       6.312   Cond. No.                     1.15e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.15e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

## Insights

In [27]:
# Masquer la fenêtre principale Tkinter
root = Tk()
root.withdraw()

# Forcer la fenêtre au premier plan
root.attributes('-topmost', True)
root.update()

# Fenêtre pour choisir où sauvegarder le fichier
chemin_fichier = filedialog.asksaveasfilename(
    title="Choisissez l'emplacement pour sauvegarder le fichier",
    defaultextension=".csv",
    filetypes=[("Fichier CSV", "*.csv"), ("Tous les fichiers", "*.*")]
)

# Sauvegarde du fichier si un chemin est sélectionné
if chemin_fichier:
    df_sample.to_csv(chemin_fichier, index=False)
    print("Fichier sauvegardé avec succès :", chemin_fichier)
else:
    print("Sauvegarde annulée")

Fichier sauvegardé avec succès : C:/Users/pc/Downloads/US_Accidents/US_Accidents_sample.csv